# Site settings

title: Sidharth Mehta
url: "https://sidharthmehta.github.io"
baseurl: ""


# The rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

markdown: kramdown
include: [_data]
